# Generated by Django 6.0.2 on 2026-02-25 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Team description",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Team logo",
                        null=True,
                        upload_to="team_logos/%Y/%m/",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow public discovery of team"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Team owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                            ("commenter", "Commenter"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Membership",
                "verbose_name_plural": "Team Memberships",
                "unique_together": {("team", "user")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="accounts.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User biography or short description",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Content Creator"),
                            ("agency", "Creative Agency"),
                            ("educator", "Educator"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        default="creator",
                        max_length=20,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Personal or business website", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="User location", max_length=100, null=True
                    ),
                ),
                (
                    "is_public_portfolio",
                    models.BooleanField(
                        default=True, help_text="Make portfolio visible to public"
                    ),
                ),
                (
                    "portfolio_theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("minimal", "Minimal"),
                        ],
                        default="light",
                        help_text="Theme for public portfolio",
                        max_length=50,
                    ),
                ),
                (
                    "total_projects",
                    models.IntegerField(
                        default=0, help_text="Total number of created projects"
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, help_text="Total portfolio views"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["owner", "is_public"], name="accounts_te_owner_i_bfbfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user", "is_public_portfolio"],
                name="accounts_us_user_id_0e2773_idx",
            ),
        ),
    ]
