# Generated by Django 6.0.2 on 2026-02-25 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Media title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Media file", upload_to="media/%Y/%m/%d/"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        help_text="Type of media",
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Make media publicly accessible"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds (for audio/video)",
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True,
                        help_text="Width in pixels (for images/video)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="Height in pixels (for images/video)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioMedia",
            fields=[
                (
                    "mediaasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.mediaasset",
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True, help_text="Artist or creator name", max_length=255
                    ),
                ),
                (
                    "album",
                    models.CharField(
                        blank=True, help_text="Album name", max_length=255
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, help_text="Music genre", max_length=100
                    ),
                ),
                (
                    "codec",
                    models.CharField(
                        blank=True, help_text="Audio codec", max_length=50
                    ),
                ),
                (
                    "bitrate",
                    models.IntegerField(
                        blank=True, help_text="Bitrate in kbps", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Media",
                "verbose_name_plural": "Audio Media",
            },
            bases=("media.mediaasset",),
        ),
        migrations.CreateModel(
            name="DocumentMedia",
            fields=[
                (
                    "mediaasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.mediaasset",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word Document"),
                            ("spreadsheet", "Spreadsheet"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        default="pdf",
                        max_length=50,
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, help_text="Number of pages", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Media",
                "verbose_name_plural": "Document Media",
            },
            bases=("media.mediaasset",),
        ),
        migrations.CreateModel(
            name="ImageMedia",
            fields=[
                (
                    "mediaasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.mediaasset",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        help_text="Image format (JPEG, PNG, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_thumbnail",
                    models.BooleanField(
                        default=False, help_text="Is this a thumbnail image"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Media",
                "verbose_name_plural": "Image Media",
            },
            bases=("media.mediaasset",),
        ),
        migrations.CreateModel(
            name="VideoMedia",
            fields=[
                (
                    "mediaasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.mediaasset",
                    ),
                ),
                (
                    "codec",
                    models.CharField(
                        blank=True, help_text="Video codec", max_length=50
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("360p", "360p"),
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                            ("4k", "4K"),
                        ],
                        default="720p",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/%Y/%m/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Media",
                "verbose_name_plural": "Video Media",
            },
            bases=("media.mediaasset",),
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=100, unique=True),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_assets",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="media.mediaasset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Tag",
                "verbose_name_plural": "Media Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMediaAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in project"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for this media in project",
                        max_length=500,
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Use as project cover image"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_projects",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Media Association",
                "verbose_name_plural": "Project Media Associations",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["owner", "file_type"], name="media_media_owner_i_dec5a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["is_public", "status"], name="media_media_is_publ_c3a869_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmediaassociation",
            unique_together={("project", "media")},
        ),
    ]
